quarkus.datasource."pg".db-kind=postgresql
quarkus.datasource."pg".devservices.image-name=postgis/postgis:18-3.6

quarkus.flyway."pg".migrate-at-start=true
quarkus.flyway."pg".locations=db/migration
quarkus.flyway."pg".baseline-on-migrate=true
quarkus.flyway."pg".baseline-version=0

%prod.quarkus.datasource."pg".username=${POSTGRES_USER}
%prod.quarkus.datasource."pg".password=${POSTGRES_PASSWORD}
%prod.quarkus.datasource."pg".jdbc.url=jdbc:postgresql://db:5432/${POSTGRES_DB}
%prod.quarkus.datasource."pg".jdbc.min-size=3
%prod.quarkus.datasource."pg".jdbc.max-size=20
%prod.quarkus.datasource."pg".jdbc.initial-size=3
